const mockups = [
    {
        name: 'Momentum',
        image:`<i class="far fa-comment"></i>`,
        description: "You're working for a company as a front-end developer. Your boss tells you that your team is putting the finishing touches on a website they've been developing; Momentum. The design team has created a mockup for the beta testing landing page for this website and your boss needs you to code it out with just HTML and CSS!",
        shortDesc: 'This was the first mockup challenge I undertook, with simple HTML and CSS and only minor changes for tablet and desktop viewports',
        html: true,
        sass: false,
        javascript: false,
        all: true,
        modalImage: 'images/momentum.png',
        codeUrl: 'https://github.com/c-tregunna/Slack-HTML-challenge',
        liveSite: 'https://c-tregunna.github.io/Slack-HTML-challenge/',
    },
    {
        name: 'Firebase',
        image:`<i class="fas fa-fire"></i>`,
        description: "You're working for a company as a front-end developer. Your boss tells you that your team is putting the finishing touches on a plugin they've been developing; fireboxjs. The design team has created a mockup for the landing page for this plugin and your boss needs you to code it out with just HTML and CSS!",
        html: true,
        sass: false,
        javascript: false,
        all: true,
        modalImage: 'images/firebase.png',
        codeUrl: 'https://github.com/c-tregunna/Slack-Firebase-Challenge',
        liveSite: 'https://c-tregunna.github.io/Slack-Firebase-Challenge/',
    },
    {
        name: 'iOS',
        image:`<i class="fas fa-mobile-alt"></i>`,
        description: "With this Mockup code challenge, I challenge you to take the iOS Settings as shown in the mockup and recreate it using HTML and CSS! This is a great time to use flexbox or even CSS Grid to structure your settings items.",
        html: true,
        sass: false,
        javascript: false,
        all: true,
        modalImage: 'images/ios.png',
        codeUrl: 'https://github.com/c-tregunna/iOS-Slack-Challenge',
        liveSite: 'https://c-tregunna.github.io/iOS-Slack-Challenge/',
    },
    {
        name: 'Cloud Flare',
        image:`<i class="fab fa-cloudversify"></i>`,
        description: "CloudFlare is a cloud storage software that will allow users to securely store their files in the cloud. You will need to recreate the mockup provided to give this web space a login page.",
        html: true,
        sass: true,
        javascript: true,
        all: true,
        modalImage: 'images/cloudflare.png',
        codeUrl: 'https://github.com/c-tregunna/CloudFlare-Challenge',
        liveSite: 'https://c-tregunna.github.io/CloudFlare-Challenge/',
    },
    {
        name: 'Social Network',
        image:`<i class="fas fa-user-friends"></i>`,
        description: "You're confident in your coding abilities and set off to build the next best social media platform! This mockup has a lot of similarities as Twitter. You'll be given a mockup for mobile devices to follow and execute with precision! You will supply your own profile picture as well as one of your recent achievements for the post that displays an achievement! Have fun with this and give it your best shot!",
        html: true,
        sass: true,
        javascript: false,
        all: true,
        modalImage: 'images/social.png',
        codeUrl: 'https://github.com/c-tregunna/Social-Challenge',
        liveSite: 'https://c-tregunna.github.io/Social-Challenge/',
    },
    {
        name: 'Paws Adoption Center',
        image:`<i class="fas fa-paw"></i>`,
        description: "You're taking your freelancing skills to the streets and noticed a pet adoption agency doesn't have a website. You offer to create one for them and sell it. They happily agree and tell you what they would like. Your job is to review the mockup and all images that the owner has provided for you. Try your best to recreate what they're asking for! You and the owner have agreed on a price but is willing to offer you more if you make it mobile friendly.The choice is up to you!",
        html: true,
        sass: true,
        javascript: false,
        all: true,
        modalImage: 'images/petadopt.png',
        codeUrl: 'https://github.com/c-tregunna/Pet_adoption_Challenge',
        liveSite: 'https://c-tregunna.github.io/Pet_adoption_Challenge/',
    },
    {
        name: 'ChatApp',
        image:`<i class="far fa-comments"></i>`,
        description: "You've been asked to create a chat interface! This will test your CSS skills by structuring multiple elements within a single container.",
        html: true,
        sass: true,
        javascript: true,
        all: true,
        modalImage: 'images/chatapp.png',
        codeUrl: 'https://github.com/c-tregunna/ChatApp-Challenge',
        liveSite: 'https://c-tregunna.github.io/ChatApp-Challenge/',
    },
    {
        name: 'FeatherLITE',
        image:`<i class="far fa-sticky-note"></i>`,
        description: "The design team at your company has come to you with some mockups for a potential note taking application your company wants to create; Feather. Feather will have two version LITE and PRO. You're tasked with creating the LITE version of this application from only these mockups and the tools you've gained during your Techdegree. Are you up for the task?",
        html: true,
        sass: true,
        javascript: true,
        all: true,
        modalImage: 'images/featherlite.png',
        codeUrl: 'https://github.com/c-tregunna/FeatherLITE-Challenge',
        liveSite: 'https://c-tregunna.github.io/FeatherLITE-Challenge/',
    },
    {
        name: 'Treehouse Landing Page',
        image:`<i class="fas fa-code"></i>`,
        description: "The project is based on the beloved Treehouse landing page for the techdegree. The page contains three widgets that you will manipulate with JavaScript to complete the functionality to the page. ",
        html: false,
        sass: false,
        javascript: true,
        all: true,
        codeUrl: 'https://github.com/c-tregunna/treehouse-widget',
        liveSite: 'https://c-tregunna.github.io/treehouse-widget'
    },
    {
        name: 'Random Meal Planner',
        image:`<i class="fas fa-book-open"></i>`,
        description: "Create a randomized meal planner that you can use to generate a weekly meal plan for the week.",
        html: false,
        sass: false,
        javascript: true,
        all: true,
    },
];

