const mockups = [
    {
        name: 'Momentum',
        image:'images/momentum.png',
        description: "You're working for a company as a front-end developer. Your boss tells you that your team is putting the finishing touches on a website they've been developing; Momentum. The design team has created a mockup for the beta testing landing page for this website and your boss needs you to code it out with just HTML and CSS!",
        html: true,
        sass: false,
        javascript: false,
    },
    {
        name: 'Firebase',
        image:'images/firebase.png',
        description: "You're working for a company as a front-end developer. Your boss tells you that your team is putting the finishing touches on a plugin they've been developing; fireboxjs. The design team has created a mockup for the landing page for this plugin and your boss needs you to code it out with just HTML and CSS!",
        html: true,
        sass: false,
        javascript: false,
    },
    {
        name: 'iOS',
        image:'images/ios.png',
        description: "With this Mockup code challenge, I challenge you to take the iOS Settings as shown in the mockup and recreate it using HTML and CSS! This is a great time to use flexbox or even CSS Grid to structure your settings items.",
        html: true,
        sass: false,
        javascript: false,
    },
    {
        name: 'Cloud Flare',
        image:'images/cloudflare.png',
        description: "CloudFlare is a cloud storage software that will allow users to securely store their files in the cloud. You will need to recreate the mockup provided to give this web space a login page.",
        html: true,
        sass: true,
        javascript: true,
    },
    {
        name: 'Social Network',
        image:'images/social.png',
        description: "You're confident in your coding abilities and set off to build the next best social media platform! This mockup has a lot of similarities as Twitter. You'll be given a mockup for mobile devices to follow and execute with precision! You will supply your own profile picture as well as one of your recent achievements for the post that displays an achievement! Have fun with this and give it your best shot!",
        html: true,
        sass: true,
        javascript: false,
    },
    {
        name: 'Paws Adoption Center',
        image:'images/petadopt.png',
        description: "You're taking your freelancing skills to the streets and noticed a pet adoption agency doesn't have a website. You offer to create one for them and sell it. They happily agree and tell you what they would like. Your job is to review the mockup and all images that the owner has provided for you. Try your best to recreate what they're asking for! You and the owner have agreed on a price but is willing to offer you more if you make it mobile friendly.The choice is up to you!",
        html: true,
        sass: true,
        javascript: false,
    },
    {
        name: 'ChatApp',
        image:'images/chatapp.png',
        description: "You've been asked to create a chat interface! This will test your CSS skills by structuring multiple elements within a single container.",
        html: true,
        sass: true,
        javascript: true,
    },
    {
        name: 'FeatherLITE',
        image:'images/featherlite.png',
        description: "The design team at your company has come to you with some mockups for a potential note taking application your company wants to create; Feather. Feather will have two version LITE and PRO. You're tasked with creating the LITE version of this application from only these mockups and the tools you've gained during your Techdegree. Are you up for the task?",
        html: true,
        sass: true,
        javascript: true,
    }
];