const mockups = [
    {
        name: 'Momentum',
        image:'images/momentum.png',
        description: "You're working for a company as a front-end developer. Your boss tells you that your team is putting the finishing touches on a website they've been developing; Momentum. The design team has created a mockup for the beta testing landing page for this website and your boss needs you to code it out with just HTML and CSS!",
        html: true,
        sass: false,
        javascript: false,
    },
    {
        name: 'Firebase',
        image:'images/firebase.png',
        description: "You're working for a company as a front-end developer. Your boss tells you that your team is putting the finishing touches on a website they've been developing; Momentum. The design team has created a mockup for the beta testing landing page for this website and your boss needs you to code it out with just HTML and CSS!",
        html: true,
        sass: false,
        javascript: false,
    },
    {
        name: 'iOS',
        image:'images/ios.png',
        description: "You're working for a company as a front-end developer. Your boss tells you that your team is putting the finishing touches on a website they've been developing; Momentum. The design team has created a mockup for the beta testing landing page for this website and your boss needs you to code it out with just HTML and CSS!",
        html: true,
        sass: false,
        javascript: false,
    },
    {
        name: 'Cloud Flare',
        image:'images/cloudflare.png',
        description: "You're working for a company as a front-end developer. Your boss tells you that your team is putting the finishing touches on a website they've been developing; Momentum. The design team has created a mockup for the beta testing landing page for this website and your boss needs you to code it out with just HTML and CSS!",
        html: true,
        sass: true,
        javascript: true,
    },
    {
        name: 'Social Network',
        image:'images/social.png',
        description: "You're working for a company as a front-end developer. Your boss tells you that your team is putting the finishing touches on a website they've been developing; Momentum. The design team has created a mockup for the beta testing landing page for this website and your boss needs you to code it out with just HTML and CSS!",
        html: true,
        sass: true,
        javascript: false,
    },
    {
        name: 'Paws Adoption Center',
        image:'images/petadopt.png',
        description: "You're working for a company as a front-end developer. Your boss tells you that your team is putting the finishing touches on a website they've been developing; Momentum. The design team has created a mockup for the beta testing landing page for this website and your boss needs you to code it out with just HTML and CSS!",
        html: true,
        sass: true,
        javascript: false,
    },
    {
        name: 'ChatApp',
        image:'images/chatapp.png',
        description: "You're working for a company as a front-end developer. Your boss tells you that your team is putting the finishing touches on a website they've been developing; Momentum. The design team has created a mockup for the beta testing landing page for this website and your boss needs you to code it out with just HTML and CSS!",
        html: true,
        sass: true,
        javascript: true,
    },
    {
        name: 'FeatherLITE',
        image:'images/featherlite.png',
        description: "You're working for a company as a front-end developer. Your boss tells you that your team is putting the finishing touches on a website they've been developing; Momentum. The design team has created a mockup for the beta testing landing page for this website and your boss needs you to code it out with just HTML and CSS!",
        html: true,
        sass: true,
        javascript: true,
    }
];